import javax.servlet.*; 
import javax.servlet.http.*; 
import java.io.*; 
public class SampleServlet extends HttpServlet 
{ 
public void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException 
{ 
PrintWriter out; 
try 
{ 
out= res.getWriter(); 
out.print("<html><head><title> Response From Servlet </title></head>"); 
out.print("<body> <p> <h3> This Text Is Generated By Invoked Servlet </h3> </body></html>"); 
} 
catch(IOException ie) 
{ 
ie.printStackTrace(); 
} } } 
